// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDSM(arg1) {
  return window['go']['main']['Api']['GetDSM'](arg1);
}

export function GetDependencyCoupling(arg1, arg2) {
  return window['go']['main']['Api']['GetDependencyCoupling'](arg1, arg2);
}

export function GetDependencyGraph(arg1) {
  return window['go']['main']['Api']['GetDependencyGraph'](arg1);
}

export function GetInstability(arg1) {
  return window['go']['main']['Api']['GetInstability'](arg1);
}

export function GetMetricsCognitiveComplexity(arg1) {
  return window['go']['main']['Api']['GetMetricsCognitiveComplexity'](arg1);
}

export function GetMetricsComments(arg1) {
  return window['go']['main']['Api']['GetMetricsComments'](arg1);
}

export function GetMetricsComplexity(arg1) {
  return window['go']['main']['Api']['GetMetricsComplexity'](arg1);
}

export function GetMetricsInterfaces(arg1) {
  return window['go']['main']['Api']['GetMetricsInterfaces'](arg1);
}

export function GetMetricsLOC(arg1) {
  return window['go']['main']['Api']['GetMetricsLOC'](arg1);
}

export function GetMetricsTypes(arg1) {
  return window['go']['main']['Api']['GetMetricsTypes'](arg1);
}

export function GetProjectInfo(arg1) {
  return window['go']['main']['Api']['GetProjectInfo'](arg1);
}

export function GetRepositoryInfo(arg1) {
  return window['go']['main']['Api']['GetRepositoryInfo'](arg1);
}

export function GetVCSAnalysisInfo(arg1, arg2) {
  return window['go']['main']['Api']['GetVCSAnalysisInfo'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['main']['Api']['SetContext'](arg1);
}
