// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnvironmentPath() {
  return window['go']['main']['App']['CheckEnvironmentPath']();
}

export function GetGoVersion() {
  return window['go']['main']['App']['GetGoVersion']();
}

export function GetProjectList() {
  return window['go']['main']['App']['GetProjectList']();
}

export function GetSelectedProject() {
  return window['go']['main']['App']['GetSelectedProject']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function RemoveSelectedProject() {
  return window['go']['main']['App']['RemoveSelectedProject']();
}

export function SaveProjectList(arg1) {
  return window['go']['main']['App']['SaveProjectList'](arg1);
}

export function SaveSelectedProject(arg1) {
  return window['go']['main']['App']['SaveSelectedProject'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}
