// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnvironmentPath() {
  return window['go']['main']['App']['CheckEnvironmentPath']();
}

export function GetGoVersion() {
  return window['go']['main']['App']['GetGoVersion']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}
