name: Test makefile on MacOS
on:
  pull_request:
    branches: [ mainX ]

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Test Makefile
        run: make install
