name: Test makefile on linux
on:
  pull_request:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Create Go Architect folder1
        run: mkdir $Env:HOMEPATH\.goarchitect

      - name: Create Go Architect folder2
        run: mkdir C:\Users\runneradmin\.goarchitect

      - name: Test Makefile
        run: make install

      - name: PWD
        run: pwd
        shell: bash

      - name: Find executable
        run: test -f /d/a/go-architect/go-architect/go-architect.exe
        shell: bash