name: Test makefile on linux
on:
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Test Makefile
        run: make install

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Get Wails Dependencies
        run: sudo apt-get install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev npm pkg-config

      - name: Test Makefile
        run: make install

      - name: Check executable
        run: ls | grep "^go-architect$"

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Check environment
        run: wails doctor

      - name: Build package windows 1
        run: wails build -platform=windows

      - name: Build package windows
        run: |
          $GP = (go env GOPATH)
          $env:path = "$env:path;$GP\bin"
          echo "building on windows"
          choco install mingw --version=11.2.0.07112021
          wails doctor
          wails build -platform=windows -clean

      - name: Test Makefile
        run: make install
