name: Release Workflow

on:
  pull_request:
    branches: [ main ]
  push:
    tags:
      - "v*.*.*"

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Check Wails Version
        run: wails version

      - name: Build Go Architect
        run: wails build -platform=darwin/arm64

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: "Go-Architect-version.zip"
          directory: /Users/runner/work/go-architect/go-architect/build/bin

      - name: Check Build
        run: ls -la /Users/runner/work/go-architect/go-architect/build/bin

#      - name: Install node-appdmg
#        run: npm install -g appdmg

#      - name: Install Create-DMG
#        run: brew install create-dmg

#      - name: Create Go Architect DMG
#        run: appdmg appdmg.json "Go-Architect-${{github.ref_name}}.dmg"

      #      - name: Create Go Architect DMG
      #        run: create-dmg "Go-Architect-${{github.ref_name}}.dmg" "/Users/runner/work/go-architect/go-architect/build/bin/Go Architect.app/"

#      - name: Save DMG Image in workspace
#        uses: actions/upload-artifact@v3
#        with:
#          name: "Go-Architect-${{github.ref_name}}.dmg"
#          path: "Go-Architect-${{github.ref_name}}.dmg"

      - name: Save Zip File in workspace
        uses: actions/upload-artifact@v3
        with:
          name: "Go-Architect-version.zip"
          path: "/Users/runner/work/go-architect/go-architect/build/bin/Go-Architect-version.zip"
