name: Test makefile for all platforms
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          node-version: 20
          go-version: 1.19

      - name: Test Makefile
        run: make install

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          node-version: 20
          go-version: 1.19

      - name: Get Wails Dependencies
        run: sudo apt-get install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev npm pkg-config

      - name: Test Makefile
        run: make install

      - name: Check executable
        run: ls | grep "^go-architect$"

  windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          node-version: 20
          go-version: 1.19

      - name: Create Go Architect folder2
        run: mkdir C:\Users\runneradmin\.goarchitect

      - name: Test Makefile
        run: make install

      - name: Check current Directory
        run: pwd
        shell: bash

      - name: Find Go-Architect executable
        run: test -f /d/a/go-architect/go-architect/go-architect.exe
        shell: bash